all:
	gcc msgq_client.c -o msgq_client.out
	gcc msgq_server.c -o msgq_server.out

client:
	gcc msgq_client.c -o msgq_client.out

server:
	gcc msgq_server.c -o msgq_server.out

runclient:
	./msgq_client.out

runserver:
	./msgq_server.out